### ISSUE TITLE
About network selection

### ISSUE THREAD

**Issue by TracyTHT** [yjwong1999/OpenCV-AI-Competition-UTAR4Vision#2]
Why is the navigation module using mobilenet-ssd network and the traffic light module using Yolov4 network? Is it based on any considerations?

**Comment by yjwong1999** [comment]
Hi @TracyTHT 

Since this project is meant for competition, it is easier for us to use pre-trained networks that are provided by the oak-d developers. One of the provided networks is the mobilenet-ssd network, which is trained for PASCAL VOC object detection. Thus, we use directly this neural network for navigation . 

On the other hand, the traffic light detection network is a YOLOv4 network that we trained ourselves. The reason why we use YOLOv4 (instead of mobilenet-ssd) for the traffic light module is purely a choice of one of our developers. Our teammate has experience training object detection model using YOLOv4. Thus, naturally it is easier for us to train YOLOv4.

Some of the improvements we/you can do are:
- trained a YOLOv4/mobilenet-ssd for object detection and traffic light detection

Thank you very much for trying our code :)
Will close the issue now
